# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  omniauth_provider_key_t: <%= ENV["OMNIAUTH_PROVIDER_KEY_TWITTER"] %>
  omniauth_provider_secret_t: <%= ENV["OMNIAUTH_PROVIDER_SECRET_TWITTER"] %>
  omniauth_provider_key_g: <%= ENV["OMNIAUTH_PROVIDER_KEY_GOOGLE"] %>
  omniauth_provider_secret_g: <%= ENV["OMNIAUTH_PROVIDER_SECRET_GOOGLE"] %>
  omniauth_provider_key_f: <%= ENV["OMNIAUTH_PROVIDER_KEY_FACEBOOK"] %>
  omniauth_provider_secret_f: <%= ENV["OMNIAUTH_PROVIDER_SECRET_FACEBOOK"] %>
  omniauth_provider_key_tumblr: <%= ENV["OMNIAUTH_PROVIDER_KEY_TUMBLR"] %>
  omniauth_provider_secret_tumblr: <%= ENV["OMNIAUTH_PROVIDER_SECRET_TUMBLR"] %>
  domain_name: example.com
  secret_key_base: d64f2836c04e932ec90d560508aec2c1db650fdc3777a8c7dcd7ddb3cda8eded3551da7a894f5d4647a4461cf65e8bbd8537d473afee79911362b37beaf6fa0e

test:
  secret_key_base: ba9b13d36f709dce8d80e1e4d332953e0237e3f155776a51db9c74178afed14f79dedadab363a55f23d091976f1a4a5951f3b2d3d0e9f0e6e0c1be0eb77cf97f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key_t: <%= ENV["OMNIAUTH_PROVIDER_KEY_TWITTER"] %>
  omniauth_provider_secret_t: <%= ENV["OMNIAUTH_PROVIDER_SECRET_TWITTER"] %>
  omniauth_provider_key_g: <%= ENV["OMNIAUTH_PROVIDER_KEY_GOOGLE"] %>
  omniauth_provider_secret_g: <%= ENV["OMNIAUTH_PROVIDER_SECRET_GOOGLE"] %>
  omniauth_provider_key_f: <%= ENV["OMNIAUTH_PROVIDER_KEY_FACEBOOK"] %>
  omniauth_provider_secret_f: <%= ENV["OMNIAUTH_PROVIDER_SECRET_FACEBOOK"] %>
  omniauth_provider_key_tumblr: <%= ENV["OMNIAUTH_PROVIDER_KEY_TUMBLR"] %>
  omniauth_provider_secret_tumblr: <%= ENV["OMNIAUTH_PROVIDER_SECRET_TUMBLR"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
